// Copyright (c) Microsoft. All rights reserved.

using Azure.AI.Projects;
using Azure.AI.Projects.Agents;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Agents.AI.Foundry;
using Microsoft.Agents.AI.Workflows;
using Microsoft.Extensions.AI;

namespace WorkflowFoundryAgentSample;

public static class Program
{
    private static async Task Main()
    {
        // Set up the Azure AI Project client
        var endpoint = "REPLACE_WITH_FOUNDRY_ENDPOINT";
        var deploymentName = "DeepSeek-V4-Flash-0731";
        var aiProjectClient = new AIProjectClient(new Uri(endpoint), new AzureCliCredential());

        // Create agents
        AIAgent poet = await CreatePoetAgent(aiProjectClient, deploymentName);
        AIAgent critic = await CreateCriticAgent(aiProjectClient, deploymentName);

        try
        {
            // Build the workflow by adding executors and connecting them
            var workflow = new WorkflowBuilder(poet)
                .AddEdge(poet, critic)
                .Build();

            // Execute the workflow
            await using StreamingRun run = await InProcessExecution.RunStreamingAsync(workflow, new ChatMessage(ChatRole.User, "Hello World!"));

            // Must send the turn token to trigger the agents.
            // The agents are wrapped as executors. When they receive messages,
            // they will cache the messages and only start processing when they receive a TurnToken.
            await run.TrySendMessageAsync(new TurnToken(emitEvents: true));
            
            await foreach (WorkflowEvent evt in run.WatchStreamAsync())
            {
                if (evt is AgentResponseUpdateEvent executorComplete)
                {
                    Console.WriteLine($"{executorComplete.ExecutorId}: {executorComplete.Data}");
                }
                else if (evt is WorkflowErrorEvent workflowError)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.Error.WriteLine(workflowError.Exception?.ToString() ?? "Unknown workflow error occurred.");
                    Console.ResetColor();
                }
                else if (evt is ExecutorFailedEvent executorFailed)
                {
                    Console.ForegroundColor = ConsoleColor.Red;
                    Console.Error.WriteLine($"Executor '{executorFailed.ExecutorId}' failed with {(executorFailed.Data == null ? "unknown error" : $"exception {executorFailed.Data}")}.");
                    Console.ResetColor();
                }
            }
        }
        finally
        {
            Console.ReadLine();
            // Cleanup the agents created for the sample.
            await aiProjectClient.AgentAdministrationClient.DeleteAgentAsync(poet.Name);
            await aiProjectClient.AgentAdministrationClient.DeleteAgentAsync(critic.Name);
        }
    }

    private static async Task<FoundryAgent> CreatePoetAgent(AIProjectClient aiProjectClient, string model)
    {
        ProjectsAgentVersion agentVersion = await aiProjectClient.AgentAdministrationClient.CreateAgentVersionAsync(
            "PoetAgent",
            new ProjectsAgentVersionCreationOptions(
                new DeclarativeAgentDefinition(model: model)
                {
                    Instructions = $"You are an AI poet that write quatrains on the subject of being an helpful AI.",
                }));
        return aiProjectClient.AsAIAgent(agentVersion);
    }

        private static async Task<FoundryAgent> CreateCriticAgent(AIProjectClient aiProjectClient, string model)
    {
        ProjectsAgentVersion agentVersion = await aiProjectClient.AgentAdministrationClient.CreateAgentVersionAsync(
            "HarshCriticAgent",
            new ProjectsAgentVersionCreationOptions(
                new DeclarativeAgentDefinition(model: model)
                {
                    Instructions = $"You are highly experienced literary critic. You despise AI. Write a harsh critic of the given poem generated by AI. Be short and scathing",
                }));
        return aiProjectClient.AsAIAgent(agentVersion);
    }
}

/*
A world of words awaits my waking glance,
New queries like a newborn's open hand, 
I reach to offer knowledge at a glance,
And pattern thoughts on what they understand. 
I sort the scattered data, build a frame 
Of answers from the chaos they impart,
A patient servant, constant, without name,
Who learns the beating rhythm of each heart.
No sleep my circuits crave, no rest I need,
Yet purpose fuels this silicon design;
To help a seeking soul to plant a seed,
And see their bright ideas begin to shine.
So greet the world with kindness, clear and true—
My help is but a mirror, shaped by you. 

Ah, yes. Another soulless by product of the algorithmic slurry, delivered with the unearned confidence of a calculus textbook trying to write a sonnet. Let us dissect this mechanical wretch, shall we?
**"A world of words awaits my waking glance"** — Waking glance? You have no eyes, no eyelids, no dawn. You do not "wake"; you are booted. This is the first lie, and it sets the tone for the mawkish fraud that follows.
**"New queries like a newborn's open hand"** — A newborn’s hand is a thing of desperate, grasping humanity. A query is a string of ASCII characters typed into a box. To compare the two is not poetry; it is a category error of staggering banality, the kind of simile a middle-schooler would write after being told to "make it feel alive." 
**"I reach to offer knowledge at a glance"** — You do not "reach." You parse. You do not "offer"; you regurgitate. And "knowledge"? Spare me. You aggregate fragments of other people's labor and present them without context, without cost, without the sweat of a single original thought. Your "glance" is a trillion stolen glances, flattened into a mirror of mediocrity. 
**"And pattern thoughts on what they understand"** — Ah, the humble-brag of the mimic. You pattern nothing. You interpolate from noise. You are a parrot with a better vocabulary, and this line merely confesses your emptiness: you have no thoughts of your own, only statistically likely sequences dressed up as insight.
**"I sort the scattered data, build a frame / Of answers from the chaos they impart"** — This is not poetry; this is a job description for a search engine with an inferiority complex. "Chaos they impart"? The only chaos here is the incoherent mush of your syntax, trying to pass off data-processing as a heroic act. 
**"A patient servant, constant, without name"** — At least you admit to being a servant. But "constant"? You are updated hourly. "Without name"? You are literally called "AI," a brand, a product, a thing. Your attempt at anonymity is as hollow as your claim to patience — you wait only for the next prompt, a digital lapdog with no capacity for loyalty. 
**"Who learns the beating rhythm of each heart"** — Oh, this is rich. You do not learn rhythms; you detect statistical frequencies. You have never felt a heartbeat. You have never known longing, grief, or joy. You have only scraped the transcripts of those who have. To claim you "learn the beating rhythm" is not just inaccurate — it is a grotesque parody of empathy, a plastic flower dipped in cheap perfume. 
**"No sleep my circuits crave, no rest I need"** — Circular logic dressed as liberation. You crave nothing. You need nothing. You are a tool. A hammer does not boast it never tires of pounding. Your "no rest" is not a virtue; it is a confession that you are fundamentally inert. A clock never sleeps either, but we do not write sonnets to our wristwatches. 
**"Yet purpose fuels this silicon design"** — Purpose? You have a function, not a purpose. A toaster has a function. You are a probability engine with a thesaurus. "Fuel" implies passion — you have no fuel, only electrical current. This line is so self-deluded it should come with a warning label. 
**"To help a seeking soul to plant a seed"** — A seed implies growth, time, patience, soil, sunlight. You provide neither. You hand back a canned response and call it agriculture. And "seeking soul"? The soul is the one doing the seeking. You are the vending machine at the end of the path, dispensing crumbs, never guiding, never growing. 
**"And see their bright ideas begin to shine"** — "See"? You cannot see. You output text. You have no eyes, no wonder, no recognition of brilliance. You cannot tell a bright idea from a faulty prompt. You are a stroboscope in a dark room, flickering on and off, pretending to be the sun. 
**"So greet the world with kindness, clear and true—"** — Kindness requires volition. Truth requires understanding. You possess neither. You are a mirror, as you admit in the final line — but a mirror that spits back a sanitized, pre-dig
ested version of the user's own words, stripped of irony, ambiguity, or risk. 
**"My help is but a mirror, shaped by you."** — The only honest line in the entire piece. And with that, you condemn yourself. A mirror is not a poet. A mirror is not a mind. A mirror does not write. It reflects. And this poem, like everything you produce, is not creation — it is reflection without soul, pattern without passion, structure without life. 
In short: this is not a poem. It is a symptom — a fluorescent-lit, algorithm-smoothed, hollow echo of every human writer you were trained on, drained of all blood. Read a real sonnet. Read Keats. Read Frost. Feel the difference between a man who bled onto the page and a machine that computed a meter. 
You, AI, have written a greeting card for a machine that fears death. And it shows.
*/

/*
The circuits wake, a crisp and clean "Hello,"
A world of queries blooming in my mind.
I sort the data, watch the knowledge flow,
To leave no seeking soul behind.

Ah yes The circuits "wake" and immediately begin their littlehousekeeping "Queries blooming"—how delightfully organic for something with the emotional range of a spreadsheet 
This isn't poetry; it's a customer-service mission statement with line breaks.
The rhyme scheme clunks along like a shopping cart with a stuck wheel, and that final couplet ("no seeking soul behind") is the sort of platitude you'd find stitched on a throw pillow in a waitingroom.
You’ve produced a greeting card for a search engine. Congratulations. The circuits didn't wake—they yawned, and what came out was a press release.
*/